apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: track-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: track-service
    spec:
      containers:
        - name: track-service
          image: prakharsrivastav/track:1
          ports:
            - name: grpc
              containerPort: 6565
